In [1]:
import numpy as np

In [2]:
import random

In [ ]:
# 1. Create a 3x3 Numpy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
# ans : 3x3 Numpy array with random integers between 1 and 100 then, interchange its rows and columns
array=np.random.randint(1,100,(3,3))
print(array)
arrayT=array.T
print(arrayT)

[[15 60 66]
 [85  3 75]
 [15 77 60]]
[[15 85 15]
 [60  3 77]
 [66 75 60]]


In [ ]:
# 2. Generate a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
# ans: a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array:
a=np.arange(10)
print(a)
b=a.reshape(2,5)
print(b)
c=b.reshape(5,2)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 3. Create a 4x4 Numpy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [25]:
# to Create a 4x4 Numpy array with random float values and adding a border of zeros around it, resulting in a 6x6 array:
a=np.random.rand(4,4)
print(a)
b=np.zeros((6,6))
b[1:-1,1:-1]=a
print(b)

[[0.12388437 0.69489916 0.52017066 0.7407346 ]
 [0.18812727 0.80232529 0.68043509 0.07491647]
 [0.54901385 0.434331   0.90327994 0.99118501]
 [0.12866019 0.93021711 0.90922529 0.89289519]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.12388437 0.69489916 0.52017066 0.7407346  0.        ]
 [0.         0.18812727 0.80232529 0.68043509 0.07491647 0.        ]
 [0.         0.54901385 0.434331   0.90327994 0.99118501 0.        ]
 [0.         0.12866019 0.93021711 0.90922529 0.89289519 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [26]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [27]:
# Using NumPy, create an array of integers from 10 to 60 with a step of 5.
array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [28]:
# 5. Create a NumPy array of strings ['python, numpy, pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [29]:
# a numpy array of string with applied transformation:
a=np.array(['python','numpy','pandas'])
print(a)
print(np.char.upper(a))
print(np.char.lower(a))
print(np.char.title(a))

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [30]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [39]:
# Generating a NumPy array of words and Inserting a space between each character of every word in the array.

words = np.array(['hello', 'world', 'numpy'])
spaced_words = np.char.join(' ', words)
print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y']


In [40]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [41]:
# two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division:
a=np.random.randint(1,10,(3,4))
b=np.random.randint(1,10,(3,4))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[6 2 5 4]
 [5 8 3 9]
 [1 8 7 7]]
[[5 8 5 3]
 [9 7 5 5]
 [6 8 5 7]]
[[11 10 10  7]
 [14 15  8 14]
 [ 7 16 12 14]]
[[ 1 -6  0  1]
 [-4  1 -2  4]
 [-5  0  2  0]]
[[30 16 25 12]
 [45 56 15 45]
 [ 6 64 35 49]]
[[1.2        0.25       1.         1.33333333]
 [0.55555556 1.14285714 0.6        1.8       ]
 [0.16666667 1.         1.4        1.        ]]


In [42]:
#  8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [43]:
#  Using NumPy to create a 5x5 identity matrix, then extract its diagonal elements:
a=np.eye(5)
print(a)
print(np.diag(a))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [44]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [47]:
# Generating a NumPy array of 100 random integers between 0 and 1000 Finding and display all prime numbers in this array:
def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Random integers array:", random_integers)
print("Prime numbers in the array:", prime_numbers)

Random integers array: [ 49 178 147 178 542  77 608 430 438 754 368 654 826 947 775 438 972 698
 564 636 516 471 362 961 742 450 634 587 731  98 759 562 487  99 297 446
 445 770 297 961 316 162 704 506 142 855 313  49 423 908 443 722 416 221
   4 780 689 266 484 622  27 185 606 211 383  56 108 178 306 102 297 719
 241 244 842 895 667 308 309 433 652 477 795 391 311 607 708 478 377 927
 563 462 338  49 157 961 898 709 111 485]
Prime numbers in the array: [947, 587, 487, 313, 443, 211, 383, 719, 241, 433, 311, 607, 563, 157, 709]


In [48]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [50]:
# Generate a NumPy array representing daily temperatures for a month
daily_temperatures = np.random.randint(22, 47, 30)  # 30 days in a month, temperatures between 15 and 35

# Calculate weekly averages
weekly_averages = []
for i in range(0, len(daily_temperatures), 7):
  week_temps = daily_temperatures[i:i+7]
  if len(week_temps) > 0:
    weekly_average = np.mean(week_temps)
    weekly_averages.append(weekly_average)


print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures: [44 24 43 41 41 25 44 23 40 36 40 42 25 28 42 40 36 44 25 45 25 38 33 46
 35 27 40 27 44 36]
Weekly Averages: [37.42857142857143, 33.42857142857143, 36.714285714285715, 35.142857142857146, 40.0]
