In [1]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [2]:
# ans: NumPy (Numerical Python) is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical
#functions to operate on these arrays. It is widely used in scientific computing and data analysis due to its efficiency and ease of use.
# Purpose of NumPy:
# 1. Efficient Array Operations: NumPy introduces the ndarray (n-dimensional array) object, which is much more efficient for handling large datasets than Python's built-in
# lists.
# 2. Mathematical and Statistical Functions: It provides a wide range of mathematical, statistical, and linear algebra functions optimized for fast computations.
# 3. Multidimensional Arrays: While Python lists are limited to one-dimensional or simple nested structures, NumPy allows easy creation and manipulation of multi-dimensional arrays
# (2D, 3D, etc.), which are essential for scientific computing.
# Advantages of NumPy:
# 1. Performance:
# a) NumPy arrays are more memory-efficient and faster than Python lists due to their contiguous memory layout.
# b) It is implemented in C, which makes it very fast for numerical operations.
# c) Vectorization: NumPy allows element-wise operations (e.g., addition, multiplication) without explicit loops, which speeds up computations.
# 2. Ease of Use:
# a) NumPy has built-in functions for complex operations like matrix multiplication, element-wise operations, broadcasting (operations on arrays of different shapes), and more,
# making coding simpler.
# b) The syntax is intuitive and allows concise code for large-scale mathematical computations.
# 3. Interoperability:
# a) NumPy is compatible with many other libraries such as Pandas, SciPy, Matplotlib, and TensorFlow. It serves as the foundation for many of these libraries in scientific
# computing, machine learning, and data analysis.
# b) It supports integration with C and C++ for performance-critical code.
# 4. Broadcasting:
# a)NumPy supports broadcasting, which allows you to perform operations on arrays of different shapes without explicitly resizing them. This reduces the need for manual loops
# and code complexity.
# 5. Memory Efficiency:
# # a) NumPy arrays require less memory because they store elements of the same type (homogeneous), unlike Python lists, which can store mixed types, leading to higher memory
# usage.
# NumPy also allows you to control the data type of the array elements, further improving memory management.
# How NumPy Enhances Python’s Capabilities for Numerical Operations:
# Faster Computation: NumPy allows numerical operations to be performed on arrays without the need for Python loops. This results in significant speed-ups, especially for
# large datasets.
# Example: Element-wise addition in a loop (slower) vs. NumPy array addition (faster).
# Using Python lists (slower)
a = [1, 2, 3]
b = [4, 5, 6]
c = [a[i] + b[i] for i in range(len(a))]

# Using NumPy (faster)
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Vectorized operation
# 2.Handling Large Data: For scientific computing tasks, where large datasets are involved, NumPy is efficient in managing large arrays or matrices in terms of both memory
# and speed.
# 3.Linear Algebra and Statistics: NumPy provides a wide range of built-in functions for linear algebra (like matrix multiplication, determinant, inverse) and statistics
# (mean, median, standard deviation) that make numerical computations easy and fast.
# 4.Integration with Other Libraries: NumPy serves as the backbone for other Python libraries used in machine learning (like TensorFlow and PyTorch), data analysis (Pandas),
# and plotting (Matplotlib). This makes NumPy indispensable for a vast range of applications.
# 5. Flexibility with Data Types: NumPy allows defining arrays with specific data types (e.g., float, int, complex), making operations faster by eliminating the need for type
# checks and conversions that occur in regular Python lists.

In [3]:
# 2. Compare and contrast p.mean( and np.average) functions in NumPy. When would you use one over the other?

In [5]:
# ans: In NumPy, both np.mean() and np.average() are used to compute the average of an array. However, they differ in their behavior and usage, particularly when it comes to
# handling weights.
# 1. np.mean():
# Functionality:
# np.mean() calculates the arithmetic mean (or average) of the array elements along a given axis.
# The arithmetic mean is simply the sum of the elements divided by the number of elements.
# Syntax:
np.mean(array, axis=None, dtype=None, keepdims=False)
# Key Features:
# a) Unweighted: It computes a simple mean, meaning it treats all elements equally without considering any weights.
# b) Axis Parameter: You can specify the axis along which the mean is computed. If no axis is specified, it computes the mean of the entire array.
# c) Output Data Type: The data type of the result can be specified using the dtype parameter
# When to Use:
# a) Use np.mean() when you want a simple, unweighted average of an array.
# b) It's the more straightforward choice when you don’t need to consider the relative importance of elements in the array.
# 2. np.average():
# Functionality:
# a) np.average() can compute a weighted average if weights are provided, or a simple arithmetic mean if no weights are given.
# b) A weighted average takes into account the relative importance of each element by multiplying each element by a given weight before averaging.
# Syntax:
np.average(array, axis=None, weights=None, returned=False)
#Key Features:
# a) Weighted: If you pass a weights parameter, np.average() will calculate a weighted average where each element contributes to the mean based on its corresponding weight.
# b) Unweighted Option: If no weights are specified, it behaves similarly to np.mean() and calculates the arithmetic mean.
# c)Returned Option: If returned=True, it will also return the sum of the weights along with the weighted average.
# When to Use:
# Use np.average() when you want to calculate a weighted average, where different elements of the array have varying importance (weights).
# If no weights are provided, it's functionally equivalent to np.mean().
# examples:
# Array
data = np.array([1, 2, 3, 4, 5])

# Simple mean
mean_value = np.mean(data)
print(mean_value)  # Output: 3.0

# Array
data = np.array([1, 2, 3, 4, 5])

# Weights
weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

# Weighted average
weighted_avg = np.average(data, weights=weights)
print(weighted_avg)  # Output: 3.6666666666666665

In [1]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [2]:
# ans: In NumPy, you can reverse an array along different axes using various methods. The most common way is to use slicing with the step parameter set to -1. Let's explore
# how to reverse arrays for both 1D and 2D cases.
# 1. Reversing a 1D NumPy Array
# A 1D array is like a simple list of numbers. You can reverse it easily using slicing.
# Method: Using Slicing
# Syntax: array[::-1]
# The -1 step size means "step backward," which reverses the array.
# Example:
import numpy as np

# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr = arr[::-1]

print(reversed_arr) # Output: [5 4 3 2 1]

# 2. Reversing a 2D NumPy Array:
# For a 2D array (a matrix), you can reverse it along different axes: rows or columns.
# Method 1: Reverse Along Rows (Flip Vertically)
# Syntax: array[::-1, :]
# This reverses the rows, keeping the columns in order
# example:
# # 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse rows (flip vertically)
reversed_rows = array_2d[::-1, :]

print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# Method 2: Reverse Along Columns (Flip Horizontally)
#Syntax: array[:, ::-1]
# This reverses the columns, keeping the rows in order.
# Reverse columns (flip horizontally)
reversed_columns = array_2d[:, ::-1]

print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]
# Method 3: Reverse Both Rows and Columns (Flip Both Vertically and Horizontally)
# Syntax: array[::-1, ::-1]
# This reverses both rows and columns, effectively reversing the entire array.
# eg:
# Reverse both rows and columns (flip both vertically and horizontally)
reversed_both = array_2d[::-1, ::-1]

print(reversed_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]



[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [3]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


In [4]:
# ans: 1. How to Determine the Data Type of Elements in a NumPy Array:
# In NumPy, each array has a specific data type (dtype) that defines the type of elements stored in the array, such as integers, floats, or booleans. You can determine the data
# type of a NumPy array using the .dtype attribute.
# Creating a NumPy array
array = np.array([1, 2, 3, 4])

# Determine the data type of elements
print(array.dtype)  # Output: int64 (or another integer type, depending on the system)

#If you want to explicitly set the data type while creating the array, you can pass the dtype parameter:
# Creating an array with float data type
array_float = np.array([1, 2, 3, 4], dtype=float)

print(array_float.dtype)  # Output: float64

# 2. Importance of Data Types in Memory Management and Performance:
# The data type (dtype) of a NumPy array plays a critical role in memory management and performance.
# A.memory management:
# Each data type requires a specific amount of memory to store each element. For example:
# a) int8: 8-bit integer, takes 1 byte per element.
# b) int32: 32-bit integer, takes 4 bytes per element.
# c) float64: 64-bit floating point number, takes 8 bytes per element.
# The more precise the data type (like float64 or int64), the more memory each element requires.
# Example: Memory Usage with Different Data Types
array_int8 = np.array([1, 2, 3, 4], dtype=np.int8)  # Each element takes 1 byte
array_float64 = np.array([1, 2, 3, 4], dtype=np.float64)  # Each element takes 8 bytes

print(array_int8.nbytes)     # Output: 4 bytes (1 byte per element)
print(array_float64.nbytes)  # Output: 32 bytes (8 bytes per element)
# Using smaller data types like int8 or float32 can save memory, especially when working with large datasets.
# However, using smaller data types can lead to overflow if the range of the values exceeds the limits of the data type (e.g., trying to store a value larger than 127 in an
# int8 array).
# B. Performance:
# Data types directly affect performance because:
# Larger data types (e.g., float64 or int64) take up more memory and can slow down computations, especially if you're working with large datasets or performing many operations.
# Smaller data types (e.g., int8, float32) allow for faster operations since they require less memory bandwidth and fewer CPU cycles.
# However, there's a trade-off between memory usage and precision:
# a) Lower precision data types (like float32) use less memory and can perform computations faster but might lose precision for large numbers.
# b) Higher precision data types (like float64) provide more accuracy but at the cost of higher memory consumption and potentially slower performance.
# Example: Performance Trade-off
# If you're working with an array of small integers (e.g., pixel values from an image), using a smaller data type like uint8 (unsigned 8-bit integer) is efficient, as it saves
# memory and speeds up computation. However, if you're dealing with very large or very small numbers (e.g., scientific data), you may need to use float64 for more precision.


int64
float64
4
32


In [5]:
#  5. Define darrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [9]:
# In NumPy, darrays typically refer to ndarrays (N-dimensional arrays), which are the core data structure provided by the library. An ndarray is a multi-dimensional,
# homogeneous array (meaning all elements are of the same data type) that is optimized for numerical and scientific computing.
# Key Features of NumPy ndarray:
# 1 Multidimensional:
# NumPy arrays can have any number of dimensions (1D, 2D, 3D, etc.). A 1D array is like a list, a 2D array is like a matrix, and 3D arrays can represent more complex data like
# volumes or images.
# 2 Homogeneous Data Type:
# All elements in a NumPy array must have the same data type. This means you can't mix integers and floats in the same array.
# 3 Efficient Memory Layout:
# NumPy arrays are stored in contiguous blocks of memory, which allows for faster access and manipulation. This is in contrast to Python lists, which are collections of pointers
# to objects in memory.
# 4 Broadcasting:
# NumPy allows for element-wise operations between arrays of different shapes and sizes without explicitly reshaping them. This is called broadcasting, and it makes array
# operations more intuitive and faster.
# 5 Vectorized Operations:
# You can perform arithmetic and logical operations directly on NumPy arrays without writing loops. This "vectorization" allows NumPy to handle operations very efficiently.
# 6 Advanced Indexing and Slicing:
# NumPy provides powerful tools for slicing and indexing, allowing you to access subarrays or modify specific elements or sections of the array.
# 7 Support for Mathematical Functions:
# NumPy offers a wide range of built-in mathematical, statistical, and linear algebra functions that are optimized for arrays, such as mean(), sum(), dot(), and sqrt().
# Data Type Flexibility:
# While the elements are homogeneous, NumPy allows you to explicitly define the data type (dtype) of elements (e.g., int32, float64, complex128). This flexibility lets you
# optimize memory usage and computational speed based on your needs.
# eg:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D NumPy array
array_2d = np
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Creating a 3D NumPy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_1d)
print(array_2d)
print(array_3d)

# Why Use NumPy Arrays (ndarray) Instead of Lists:
# 1 Performance: For large datasets and numerical computations, NumPy is significantly faster than Python lists because of its memory efficiency and vectorized operations.
# 2 Convenience: NumPy provides built-in mathematical functions and supports matrix operations, broadcasting, and advanced slicing, which makes it much more powerful and
# convenient for scientific computing.
# Memory Efficiency: NumPy arrays use less memory due to their fixed data type and contiguous memory layout, which is important when dealing with large datasets.

# Example: Performance Comparison:
# 1. Vectorized Operations with NumPy Arrays:
# NumPy array
array = np.array([1, 2, 3, 4, 5])

# Multiply all elements by 2 (vectorized operation)
result = array * 2

print(result)  # Output: [ 2  4  6  8 10]

# 2. Similar Operation with Python Lists (Using Loops):
# Python list
list_ = [1, 2, 3, 4, 5]

# Multiply all elements by 2 (using a loop)
result = [x * 2 for x in list_]

print(result)  # Output: [2, 4, 6, 8, 10]

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[ 2  4  6  8 10]
[2, 4, 6, 8, 10]


In [10]:
# 6. Analyze the performance benefits of Numpy arrays over Python lists for large-scale numerical operations.


In [12]:
# ans: NumPy arrays provide significant performance benefits over Python lists, especially for large-scale numerical operations. These advantages come from the way NumPy is
# designed to handle data more efficiently in memory and perform operations faster. Let's break down the key performance benefits:
# 1. Memory Efficiency:
# NumPy arrays use contiguous memory allocation, and all elements in the array are of the same data type (homogeneous). This allows NumPy to store elements more compactly
# compared to Python lists, where each element is a separate object with additional overhead.
# Example: Memory Efficiency
# a) A NumPy array with 1,000,000 integers (e.g., int32) will require 4 MB (1,000,000 × 4 bytes).
# b) A Python list with the same number of integers can take up much more memory due to the overhead of storing pointers and type information for each element.
# import sys

# NumPy array with 1,000,000 integers
import sys
array = np.arange(1000000, dtype=np.int32)
print(array.nbytes)  # Output: 4000000 bytes (4 MB)

# Python list with 1,000,000 integers
list_ = list(range(1000000))
print(sys.getsizeof(list_))  # Output: Larger than 4 MB due to overhead

# 2. Vectorized Operations:
# NumPy allows you to perform vectorized operations, meaning you can apply operations on entire arrays without using explicit loops. This eliminates the need for slow Python
# loops and allows NumPy to use highly optimized, compiled C code under the hood, leading to much faster execution.
# Let’s compare the time taken to multiply each element of a large list or array by 2
import time

# Large data (10 million elements)
data_size = 10000000
array = np.arange(data_size)
list_ = list(range(data_size))

# NumPy vectorized multiplication
start = time.time()
array_result = array * 2  # Vectorized operation
end = time.time()
print("NumPy time:", end - start)

# Python list multiplication (using a loop)
start = time.time()
list_result = [x * 2 for x in list_]  # Loop-based operation
end = time.time()
print("Python list time:", end - start)

# Results:
# NumPy's vectorized operation is much faster because it avoids the overhead of looping and runs optimized, compiled code.
# Python lists, on the other hand, require a loop, which is slower, especially as the dataset size grows.
# 3. Speed and Efficiency:
# Since NumPy is implemented in C and makes use of SIMD (Single Instruction, Multiple Data) and BLAS (Basic Linear Algebra Subprograms) libraries, it can take advantage of
# low-level optimizations for mathematical operations. This makes NumPy significantly faster for computations like matrix multiplication, element-wise operations, and linear
# algebra compared to Python lists.
# Example: Matrix Multiplication Speed
# Let’s compare the time taken to perform matrix multiplication on NumPy arrays vs. Python lists..

# Create large NumPy arrays and lists
n = 1000
matrix_np = np.random.rand(n, n)
matrix_list = [[matrix_np[i][j] for j in range(n)] for i in range(n)]

# NumPy matrix multiplication
start = time.time()
result_np = np.dot(matrix_np, matrix_np)
end = time.time()
print("NumPy matrix multiplication time:", end - start)

# Python list matrix multiplication (requires manual looping)
def matrix_multiply(mat1, mat2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*mat2)] for row in mat1]
    return result

start = time.time()
result_list = matrix_multiply(matrix_list, matrix_list)
end = time.time()
print("Python list matrix multiplication time:", end - start)

# Results:
# NumPy’s matrix multiplication is orders of magnitude faster than using nested loops in Python lists, especially for large matrices, because NumPy can use highly optimized
# matrix libraries like BLAS and LAPACK.

# 4. Broadcasting:
# NumPy arrays support broadcasting, which allows operations to be performed on arrays of different shapes without the need to explicitly reshape or copy data. This feature
# is not available in Python lists, where such operations would require manual iteration and handling.

# Example: Broadcasting
# NumPy array and scalar
array = np.array([1, 2, 3, 4, 5])

# Broadcasting allows scalar multiplication
result = array + 5
print(result)  # Output: [6 7 8 9 10]

# In Python lists, you'd need to loop through each element
list_ = [1, 2, 3, 4, 5]
result_list = [x + 5 for x in list_]
print(result_list)  # Output: [6, 7, 8, 9, 10]

# In NumPy, broadcasting happens automatically and efficiently, while in Python lists, you'd need explicit loops.

# 5. Advanced Operations and Libraries:
# NumPy is integrated with many libraries (e.g., SciPy, Pandas, TensorFlow) that rely on efficient numerical computation. Complex operations like Fourier transforms, linear
# algebra, and random number generation are optimized in NumPy and take advantage of the array structure. Achieving the same with Python lists would require custom implementat
#-ions, which would be slower and error-prone.



4000000
8000056
NumPy time: 0.07558965682983398
Python list time: 2.0036280155181885


In [1]:
# 7. Compare vstack) and hstack) functions in NumPy. Provide examples demonstrating their usage and output.

In [2]:
# ans: In NumPy, the functions vstack() and hstack() are used to stack arrays along different axes (vertically and horizontally). Here's a comparison and explanation with
# examples:
# 1. vstack() (Vertical Stack):
# Purpose: Stacks arrays vertically (along the rows, i.e., axis=0). It essentially appends arrays on top of each other.
# Shape Requirement: The arrays must have the same number of columns (second dimension) to be stacked vertically.
import numpy as np

# Two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack them vertically
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Here, vstack() places arr2 below arr1, creating a 2x3 array.

# 2D Arrays Example:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])

result_vstack_2D = np.vstack((arr3, arr4))
print(result_vstack_2D)
# Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

# Here, arr4 is stacked below arr3, creating a 4x3 array.

# 2. hstack() (Horizontal Stack):
# Purpose: Stacks arrays horizontally (along the columns, i.e., axis=1). It appends arrays side by side.
# Shape Requirement: The arrays must have the same number of rows (first dimension) to be stacked horizontally.
#Example of hstack():
# Two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack them horizontally
result_hstack = np.hstack((arr1, arr2))
print(result_hstack)
# Output:
# [1 2 3 4 5 6]

# Here, hstack() places arr2 to the right of arr1, creating a 1D array with 6 elements.

# 2D Arrays Example:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])

result_hstack_2D = np.hstack((arr3, arr4))
print(result_hstack_2D)
# Output:
# [[ 1  2  3  7  8  9]
#  [ 4  5  6 10 11 12]]

# Here, arr4 is stacked to the right of arr3, creating a 2x6 array.

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [3]:
# 8. Explain the differences between flipir ) and flipud) methods in NumPy, including their effects on various array dimensions.

In [4]:
# In NumPy, the functions flipud() and fliplr() are used to flip arrays along different axes. Here's an explanation of the differences between them and how they work on arrays
# of various dimensions:
# 1. flipud() (Flip Up-Down):
# Purpose: This function flips an array vertically, meaning it reverses the order of the rows (up to down)
# Effect: The last row becomes the first, the second-to-last becomes the second, and so on. It does not affect the columns.
# Axis: It operates along the first axis (axis=0).
# Example with a 2D Array:
import numpy as np

# 2D array (3x3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Apply flipud (flip rows up-down)
result_flipud = np.flipud(arr)
print(result_flipud)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# In this example, the array is flipped vertically (rows reversed), but the order of columns in each row remains unchanged.

# Example with a 1D Array:
arr_1d = np.array([1, 2, 3, 4, 5])

result_flipud_1d = np.flipud(arr_1d)
print(result_flipud_1d)
# Output:
# [5 4 3 2 1]

# For 1D arrays, flipud() behaves similarly to reversing the array.

# 2. fliplr() (Flip Left-Right):
# Purpose: This function flips an array horizontally, meaning it reverses the order of the columns (left to right).
# Effect: The last column becomes the first, the second-to-last becomes the second, and so on. It does not affect the rows.
# Axis: It operates along the second axis (axis=1).
# Example with a 2D Array:
# 2D array (3x3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Apply fliplr (flip columns left-right)
result_fliplr = np.fliplr(arr)
print(result_fliplr)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# In this example, the array is flipped horizontally (columns reversed), but the order of rows remains unchanged.

# Example with a 1D Array:
# For a 1D array, fliplr() will throw an error because it operates along the second axis (axis=1), and 1D arrays do not have multiple axes.


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[5 4 3 2 1]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [5]:
# 9. Discuss the functionality of the array _split method in NumPy. How does it handle uneven splits?

In [9]:
# The numpy.array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike the similar split() method, array_split() can handle uneven splits,
#  meaning that if the array cannot be split into equal-sized chunks, some sub-arrays will have more elements than others

# Functionality of array_split()
# Syntax:
# numpy.array_split(array, sections, axis=0)

# array: The input array to be split.
# sections: The number of sections or the indices at which the split is made.
# axis: The axis along which to split the array (defaults to 0, which means rows in 2D arrays).
# Key Features:
# 1. Handles Uneven Splits: If the array length is not evenly divisible by the number of sections, some of the resulting sub-arrays will have more elements than others.
# 2. Flexible Number of Sections: You can specify the exact number of sections, and NumPy will distribute the elements as evenly as possible.
# Example: Even Split
# if the array can be split evenly, array_split() behaves like split().
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
result = np.array_split(arr, 3)
print(result)
# Output:
# [array([1, 2]), array([3, 4]), array([5, 6])]

# In this case, the array of 6 elements is split into 3 equal parts, each containing 2 elements.
# Example: Uneven Split :
# If the array cannot be split evenly, some sub-arrays will have more elements than others.
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split into 3 parts
result = np.array_split(arr, 3)
print(result)
# Output:
# [array([1, 2, 3]), array([4, 5]), array([6, 7])]

# ere, the array has 7 elements, which can't be evenly divided into 3 parts.
# array_split() automatically distributes the elements as evenly as possible:
# The first part gets 3 elements, and the other two get 2 elements each.
# Handling Uneven Splits:
# When the number of elements is not divisible by the number of sections:
# The first few sub-arrays will have more elements than the rest.
# NumPy divides the elements as evenly as possible.
# For example, if you split an array of 10 elements into 4 sections:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split into 4 parts
result = np.array_split(arr, 4)
print(result)
# Output:
# [array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([9, 10])]

# The first two sub-arrays have 3 elements each.
# The last two sub-arrays have 2 elements each.

# Splitting Along Different Axes:
# array_split() can also split multi-dimensional arrays along a specified axis.
# Example: 2D Array Split Along Rows (axis=0):
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Split into 3 parts along rows
result = np.array_split(arr_2d, 3, axis=0)
print(result)
# Output:
# [array([[1, 2, 3], [4, 5, 6]]),
#  array([[7, 8, 9]]),
#  array([[10, 11, 12]])]

# Here, the array is split into 3 parts along the rows.
# Example: Split Along Columns (axis=1):
# Split into 2 parts along columns
result = np.array_split(arr_2d, 2, axis=1)
print(result)
# Output:
# [array([[ 1,  2],
#         [ 4,  5],
#         [ 7,  8],
#         [10, 11]]),
#  array([[ 3],
#         [ 6],
#         [ 9],
#         [12]])]

# The array is split into 2 parts along the columns (axis=1).
# The first part has the first two columns, and the second part has the last column.


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [10]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [ ]:
# In NumPy, vectorization and broadcasting are two fundamental concepts that make numerical operations efficient by leveraging underlying optimizations. They enable fast array
# operations without the need for explicit loops, which is particularly useful when dealing with large datasets.
# 1. Vectorization:
# Vectorization refers to the process of applying operations to entire arrays (vectors, matrices, etc.) without writing explicit loops. Instead of processing individual elements
# in an array one at a time, NumPy performs operations on the whole array in one go. This is possible due to NumPy’s implementation in C and Fortran, which allows it to run
# faster compared to standard Python loops.

# Benefits of Vectorization:
# Speed: It eliminates the need for explicit Python loops, making operations much faster, especially with large datasets.
# Simplicity: Code becomes more concise and readable, as complex operations can be written in a single line.

# Example of Vectorization:
# Without vectorization (using a Python loop):
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Manually square each element
for i in arr:
    result.append(i**2)
print(result)  # Output: [1, 4, 9, 16, 25]

# With vectorization:
# Using NumPy's vectorized operation
result = arr ** 2
print(result)  # Output: [ 1  4  9 16 25]

# Key Point: The vectorized operation (arr ** 2) applies to all elements in the array without a loop, making it faster and more efficient

# 2. Broadcasting:
# Broadcasting is a mechanism that allows NumPy to perform element-wise operations on arrays with different shapes by “stretching” or broadcasting the smaller array to match
# the shape of the larger array. Instead of replicating the smaller array to make it the same size, NumPy uses broadcasting to compute the result efficiently.

#Broadcasting Rules:
# When performing operations between arrays of different shapes, NumPy applies the following rules:
# 1. If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on its left side.
# 2. Arrays are compatible in a dimension if they have the same size or one of them is 1
# 3. If the shapes are compatible after applying these rules, NumPy broadcasts the smaller array to match the shape of the larger one.

# Example of Broadcasting:
# Consider adding a scalar to an array:
arr = np.array([1, 2, 3])
scalar = 10

# Broadcasting the scalar to match the shape of the array
result = arr + scalar
print(result)  # Output: [11 12 13]

# Here, scalar is automatically “broadcast” to match the shape of arr, as if you added np.array([10, 10, 10]) to arr.

# Example with 2D and 1D Arrays:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([1, 2, 3])

# Broadcasting the vector to the shape of the matrix
result = matrix + vector
print(result)
# Output:
# [[ 2  4  6]
#  [ 5  7  9]
#  [ 8 10 12]]

# Here, the 1D vector is broadcast to the shape of the 2D matrix, and element-wise addition is performed.
# Broadcasting in Different Shapes:
# When arrays with different shapes are combined, NumPy aligns them as follows:

arr1 = np.array([[1], [2], [3]])  # Shape: (3, 1)
arr2 = np.array([10, 20, 30])     # Shape: (3,)

result = arr1 + arr2
print(result)
# Output:
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

# Here, arr1 has shape (3, 1) and arr2 has shape (3,). The second array is broadcast along the columns of the first array, resulting in a shape of (3, 3).
